### ISSUE TITLE
gdkpixbufoverlay

### ISSUE THREAD

**Issue by 9000h** [rofehr/gstreamerdevice#7]
https://github.com/rofehr/gstreamerdevice/blob/4e6c4dd8f871b5c756dc2a3ccbe93ade8ffa9931/cGstreamerDevice.c#L217

https://github.com/Parrot-Developers/disco-opensource/blob/405ca85e1e9f71441b86360c67ff4839a96f6106/sources/gst-plugins-good-1.8.3/gst-plugins-good-1.8.3/tests/icles/gdkpixbufoverlay-test.c#L204

may help to get it done

**Comment by rofehr** [comment]
I#m not sure witch way to go, mix OSD into stream, or OSd as seperate Xwindow

**Comment by rofehr** [comment]
I think the better way, is to make the OSD as stand alone window.
Because, if there is no stream, I have to make a loop (black-screen) to display the OSD.

**Comment by 9000h** [comment]
you are probably right gst seems to bee a bit strange :-/
